### ISSUE TITLE
Using 2 devices/CBA pedals simultaneously 

### ISSUE THREAD

**Issue by forcedmeme** [jehrich/max-bliss#3]
Hi there! I'm just posting here on the off chance that you'll know how to help me.

I'm using 2 chase bliss pedals and I've got the MIDIbox connected to my laptop. I don't have a problem when using them individually with these patches, but when I try to use more than 1 pedal plugged in at a time, they both respond to the same MIDI CCs.

I\m trying to get your devices to send their' output on a different MIDI channels, so that I can have each pedal on its' own discreet channel, but no matter what I do, they always send their MIDI over channel 1!

Any idea how I might achieve this? Or how are you operating more than 1 chase bliss pedal? 

Thanks!

**Comment by jehrich** [comment]
There are a few steps needed to achieve this:

1. Create a separate MIDI track in Ableton Live for each device.
2. Add the appropriate Max Bliss device to each channel.
3. Set the desired MIDI channel for each track at the bottom of the In/Out section (Midi To > Output Type > Output Channel)
4. Set the CBA pedals to the corresponding MIDI channels. 

You'll find detailed instructions for changing the channel in the CBA MIDI manual for each pedal, but it goes something like this: 

- Hold both stomp switches while powering on the pedal. The pedal starts listening for a program change message.
- Send a program change message on the channel you want the pedal to adopt (you can do this by changing the preset number on the Max Bliss device since this triggers a program change message).

Good luck!

**Comment by forcedmeme** [comment]
Hi, thanks for getting back to me!

I should have said in my first post, I've already tried the basics to get MIDI to send to different channels. To elaborate: Ive got one CBA control device on one MIDI track, sending MIDI via channel 1; no problem, it sends MIDI via the correct channel.

Then, if I add a 2nd device on a 2nd MIDI track, and try to send MIDI via channel 2; it sends MIDI via channel 2 _and channel 1 at the same _time_._

This is a strange behaviour and I really can't understand why it's happening. But as a point of reference, if I use another max device on the 2nd MIDI track, it will send its' MIDI via the channel I specified in the track output **only**, there's something about these particular devices that's stopping me from doing that. I just can't figure out what.

Maybe it's an Ableton bug, but I can't seem to replicate it with any other max/MIDI devices.

https://user-images.githubusercontent.com/36924802/136660322-58368088-fb1e-4bfb-ba89-8e02eb5b7da3.mov

I recorded a quick screen-grab showing what I'm talking about, I hope this shows it clearly enough.

**Comment by jehrich** [comment]
That looks very much like a bug in my intra-device message routing... I'll investigate and post an update here when I've found it. Thanks for reporting it!

**Comment by jehrich** [comment]
I have updated the M4L devices so that there should be no more "crosstalk" between them. I don't have access to my CBA devices at the moment, so was unable to test, but I think this will solve the problem. LMK if you have any more trouble after updating.

**Comment by forcedmeme** [comment]
Nice work! It seems to be working fine now with the MOOD device. So the fix was as simple as adding "---"?

**Comment by jehrich** [comment]
Yes, that makes the send/receive names unique within the device instance, preventing them from communicating with other devices in the same set. Without the prefix they act as global send/receive pair. Useful for inter-device messages, but not for this case :-)
